services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3030:3030
    depends_on:
      - postgres # Service defined in `docker-compose.yml`
    environment:
      - RUST_LOG=info
    restart: unless-stopped
