services:
  backend:
    build:
      context: .
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data:rw"
    environment:
      - "POSTGRES_PASSWORD=mypassword"
 
volumes:
  postgres-data:

